directories:
  output: dist_installer
  buildResources: build
appId: com.ferramentasderede.app
productName: Ferramentas de Rede
asar: false
files:
  - filter:
      - dist-electron/**/*
      - dist/**/*
win:
  target: dir
  icon: public/electron-vite.svg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
electronVersion: 30.5.1
